name: Fork Filter lists

on:
  workflow_dispatch: # 启用手动触发
  schedule:
    - cron: "0 */6 * * *" # 每隔6小时执行一次

jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4.1.0
        with:
          repository: blackspacee/Surge
          path: Surge-repo


      - name: Download files to Ruleset
        run: |
          # Apple
          curl -L -o Surge-repo/Ruleset/ApplePush.list "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/ApplePushNotificationService.list"
          curl -L -o Surge-repo/Ruleset/Apple.list "https://raw.githubusercontent.com/NobyDa/Script/master/Surge/Apple.list"

          # OpenAI
          curl -L -o Surge-repo/Ruleset/ChatGPT_Voice.list "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/ChatGPT_Voice.list"
          curl -L -o Surge-repo/Ruleset/OpenAI.list "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/OpenAI.list"
          
          # 社交媒体
          curl -L -o Surge-repo/Ruleset/Telegram.list "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Rules/Telegram.list"

          # 微软
          curl -L -o Surge-repo/Ruleset/Copilot.list "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/Copilot.list"

          # 流媒体
          curl -L -o Surge-repo/Ruleset/Emby.list "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Rules/Emby.list"

          # Talkatone
          curl -L -o Surge-repo/Ruleset/Talkatone.list "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Rules/Talkatone.list"

          # 国内规则
          mkdir -p Surge-repo/Ruleset/ChinaDomain
          curl -L -o Surge-repo/Ruleset/ChinaDomain/ChinaDomain.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

          # LAN
          curl -L -o Surge-repo/Ruleset/LAN "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Rules/Lan.list"

          # ASN
          mkdir -p Surge-repo/Ruleset/ASN
          curl -L -o Surge-repo/Ruleset/ASN/ASN.Telegram.list "https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.Telegram.list"
          curl -L -o Surge-repo/Ruleset/ASN/ASN.China.list "https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.China.list"

          # 广告规则
          mkdir -p Surge-repo/Ruleset/Advertising
          curl -L -o Surge-repo/Ruleset/Advertising/Ads_Dlerio.list "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Reject.list"
          curl -L -o Surge-repo/Ruleset/Advertising/AdGuardChinese.list "https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/chinese-filter.txt"
          curl -L -o Surge-repo/Ruleset/Advertising/Ads_EasyListChina.list "https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/rule/Surge/easylistchina_surge.list"
          curl -L -o Surge-repo/Ruleset/Advertising/Ads_EasyListPrivacy.list "https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/rule/Surge/easyprivacy_surge.list"
          curl -L -o Surge-repo/Ruleset/Advertising/Ads_limbopro.list "https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo_surge.list"
          curl -L -o Surge-repo/Ruleset/Advertising/Ads_anti_AD.list "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt"
          curl -L -o Surge-repo/Ruleset/Advertising/Ads_AdRules.list "https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list"

          # fmz200&wala
          mkdir -p Surge-repo/Ruleset/fmz200
          curl -L -o Surge-repo/Ruleset/fmz200/Direct_fmz200.list "https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/filter/fenliuxiuzheng.list"
          curl -L -o Surge-repo/Ruleset/fmz200/Ads_fmz200.list "https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/filter/fenliu.list"
          curl -L -o Surge-repo/Ruleset/fmz200/Ads_RuCu6.list "https://raw.githubusercontent.com/RuCu6/QuanX/main/Rules/MyBlockAds.list"

          # 神机规则修正
          curl -L -o Surge-repo/Ruleset/Unbreak.list "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list"

          # ConnersHua
          mkdir -p Surge-repo/Ruleset/ConnersHua
          curl -L -o Surge-repo/Ruleset/ConnersHua/Ads_ConnersHua.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list"
          curl -L -o Surge-repo/Ruleset/ConnersHua/Hijacking_ConnersHua.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Hijacking.list"
          curl -L -o Surge-repo/Ruleset/ConnersHua/Tracking_ConnersHua.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Tracking.list"

      - name: Checkout ios_rule_script Repository
        uses: actions/checkout@v2
        with:
          repository: blackmatrix7/ios_rule_script
          path: tmp # 临时存放目录

      - name: Copy Selected Folders
        run: |
          cp -r tmp/rule/Surge/WeChat Ruleset/
          cp -r tmp/rule/Surge/Zhihu Ruleset/
          cp -r tmp/rule/Surge/Speedtest Ruleset/

          cp -r tmp/rule/Surge/Spotify Ruleset/
          cp -r tmp/rule/Surge/OpenAI Ruleset/
          cp -r tmp/rule/Surge/Telegram Ruleset/
          cp -r tmp/rule/Surge/TikTok Ruleset/
          cp -r tmp/rule/Surge/Netflix Ruleset/
          cp -r tmp/rule/Surge/PayPal Ruleset/
          cp -r tmp/rule/Surge/Cloudflare Ruleset/
          cp -r tmp/rule/Surge/Twitter Ruleset/
          cp -r tmp/rule/Surge/Instagram Ruleset/
          cp -r tmp/rule/Surge/Facebook Ruleset/

          cp -r tmp/rule/Surge/GitHub Ruleset/
          cp -r tmp/rule/Surge/OneDrive Ruleset/
          cp -r tmp/rule/Surge/Bing Ruleset/
          cp -r tmp/rule/Surge/Microsoft Ruleset/

          cp -r tmp/rule/Surge/YouTube Ruleset/
          cp -r tmp/rule/Surge/Google Ruleset/

          cp -r tmp/rule/Surge/Emby Ruleset/

          cp -r tmp/rule/Surge/AppleID Ruleset/
          cp -r tmp/rule/Surge/AppStore Ruleset/
          cp -r tmp/rule/Surge/AppleMusic Ruleset/
          cp -r tmp/rule/Surge/TestFlight Ruleset/
          cp -r tmp/rule/Surge/AppleMail Ruleset/
          cp -r tmp/rule/Surge/iCloud Ruleset/
          cp -r tmp/rule/Surge/Apple Ruleset/

          cp -r tmp/rule/Surge/GlobalMedia Ruleset/
        shell: bash

      - name: Move ios_rule_script content to Surge-repo/Ruleset
        run: |
          rsync -a --exclude 'README.md' Ruleset/* Surge-repo/Ruleset/
        shell: bash

      # 适配 nice和wala  Surge 规则
      - name: Edit Ruleset/fmz200&wala
        run: |
          cd Surge-repo/Ruleset/fmz200
          for file in *.list; do
            if [ -f "$file" ]; then
            # 修改，& ; 以及大小写
            sed -i -e 's/, /,/g' -e 's/;/# /g' -e 's/host,/HOST,/g' -e 's/host-/HOST-/g'  -e 's/suffix/SUFFIX/g' -e 's/-keyword/-KEYWORD/g' -e 's/,reject/,REJECT/g' -e 's/ip-cidr/IP-CIDR/g' -e 's/geoip/GEOIP/g' "$file"
            # 删除“,REJECT”
            sed -i 's/,REJECT//g' "$file"
            # 修改HOST为DOMAIN
            sed -i -e 's/HOST,/DOMAIN,/g' -e 's/HOST-/DOMAIN-/g' "$file"
            # 修改IP6-CIDR为IP-CIDR6
            sed -i 's/IP6-CIDR,/IP-CIDR6,/g' "$file"
            # 如果包含IP-CIDR且不包含,no-resolve 则添加,no-resolve
            awk '/^IP-CIDR/ && !/,no-resolve/ {print $0",no-resolve"; next} {print}' "$file" > tmpfile
            mv tmpfile "$file"
            # 删除带有# UPDATED:字样的行
            awk '!/# UPDATED:/' "$file" > tmpfile
            mv tmpfile "$file"
          else
            echo "$file not found."
          fi
          done

      # 适配 AdGuard Surge 规则
      - name: Edit Ruleset/AdGuardChinese.list
        run: |
          cd Surge-repo/Ruleset/Advertising
          for file in AdGuardChinese.list; do
            if [ -f "$file" ]; then
            # 将每一行的第一个.替换为 DOMAIN-SUFFIX,
            sed -i 's/^\./DOMAIN-SUFFIX,/g' "$file"
            else
              echo "$file not found."
            fi
          done

        # Surge 规则添加 extended-matching
#    - name: Edit Surge/Rules add extended-matching
#      run: |
#        cd Tool-repo/Surge/Rules
#        for file in Ads_*.list  WeChat.list Tracking_*.list Hijacking_*.list Bilibili.list Netflix.list; do
#          if [ "$file" != "Ads_QQMusic.list" ] && [ "$file" != "ChatGPT_Voice.list" ]; then
            # 在包含 DOMAIN 的行的最后面添加 ,extended-matching
#            sed -i -e '/^DOMAIN-SUFFIX,/ s/$/,extended-matching/' \
#                    -e '/^DOMAIN,/ s/$/,extended-matching/' \
#                    -e '/^\./ s/$/,extended-matching/' "$file"
#          else
#            echo "$file not found."
#          fi
#        done


        # 追加规则
      - name: Output Direct.list
        run: |
          mkdir -p Surge-repo/Ruleset/Own/
          touch Surge-repo/Ruleset/Own/Direct.list

          if [ -f "Surge-repo/Ruleset/Own/Direct.list" ] ; then
            # 清空 Direct.list 文件
            > Surge-repo/Ruleset/Own/Direct.list

            cat Surge-repo/Ruleset/Unbreak.list >> Surge-repo/Ruleset/Own/Direct.list
            echo "#############" >> Surge-repo/Ruleset/Own/Direct.list
            cat Surge-repo/Ruleset/fmz200/Direct_fmz200.list >> Surge-repo/Ruleset/Own/Direct.list
          else
            echo "$file not found."
          fi
          
      - name: output Reject.list
        run: |
          touch Surge-repo/Ruleset/Own/Reject.list

          if [ -f "Surge-repo/Ruleset/Own/Reject.list" ] ; then
              # 清空 Reject.list 文件
              > Surge-repo/Ruleset/Own/Reject.list

            cat Surge-repo/Ruleset/fmz200/Ads_RuCu6.list >> Surge-repo/Ruleset/Own/Reject.list
            echo "#############" >> Surge-repo/Ruleset/Own/Reject.list
            cat Surge-repo/Ruleset/ConnersHua/Ads_ConnersHua.list >> Surge-repo/Ruleset/Own/Reject.list
            echo "#############" >> Surge-repo/Ruleset/Own/Reject.list
            cat Surge-repo/Ruleset/ConnersHua/Hijacking_ConnersHua.list >> Surge-repo/Ruleset/Own/Reject.list
            echo "#############" >> Surge-repo/Ruleset/Own/Reject.list
            cat Surge-repo/Ruleset/ConnersHua/Tracking_ConnersHua.list >> Surge-repo/Ruleset/Own/Reject.list
          else
            echo "$file not found."
          fi




      - name: Commit and Push Changes
        run: |
          cd Surge-repo
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add Ruleset/
            git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi

      - name: Cleanup Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
